# Generated by Django 3.1.7 on 2021-04-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf_web', '0002_roomreservations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservations',
            old_name='room_id',
            new_name='room',
        ),
    ]
