# Generated by Django 3.1.7 on 2021-04-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_web', '0003_auto_20210416_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservations',
            name='date',
            field=models.DateField(),
        ),
    ]
